// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeoTm7QCDXCFrLpKraTB2nf_fzvIqCgZg',
    appId: '1:693886142798:web:0c1fcc0a063ced0596f61f',
    messagingSenderId: '693886142798',
    projectId: 'choyxona-uz-app',
    authDomain: 'choyxona-uz-app.firebaseapp.com',
    storageBucket: 'choyxona-uz-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg_BsTHI8mOg33bG8dUGJUknXRkwpR-5o',
    appId: '1:693886142798:android:3b070e6ab00d402196f61f',
    messagingSenderId: '693886142798',
    projectId: 'choyxona-uz-app',
    storageBucket: 'choyxona-uz-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA_V3FO7-s9RN0fBwqZYV-nJaruYmi7AY',
    appId: '1:693886142798:ios:fbd36595c476f3eb96f61f',
    messagingSenderId: '693886142798',
    projectId: 'choyxona-uz-app',
    storageBucket: 'choyxona-uz-app.firebasestorage.app',
    iosBundleId: 'com.example.choyxonaUz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA_V3FO7-s9RN0fBwqZYV-nJaruYmi7AY',
    appId: '1:693886142798:ios:fbd36595c476f3eb96f61f',
    messagingSenderId: '693886142798',
    projectId: 'choyxona-uz-app',
    storageBucket: 'choyxona-uz-app.firebasestorage.app',
    iosBundleId: 'com.example.choyxonaUz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeoTm7QCDXCFrLpKraTB2nf_fzvIqCgZg',
    appId: '1:693886142798:web:7435c6c4991b810096f61f',
    messagingSenderId: '693886142798',
    projectId: 'choyxona-uz-app',
    authDomain: 'choyxona-uz-app.firebaseapp.com',
    storageBucket: 'choyxona-uz-app.firebasestorage.app',
  );
}
